name: getapps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  asp: ^2.0.3
  async: ^2.11.0
  auto_injector: ^2.0.5
  flutter:
    sdk: flutter
  flutter_isolate: ^2.1.0
  result_dart: ^1.1.1
  routefly: ^2.0.4
  uno: ^1.1.12
  uicons: ^1.0.1
  gap: ^3.0.1
  image: ^4.2.0
  android_package:
    path: plugins/android_package
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
